[package]
name = "cch"
version = "2023.12.9-2"
authors = ["Francisco Nevitt Gonçalves <github.com/fng97>"]
edition = "2021"

[dependencies]
actix-web = "4.4.0"
shuttle-actix-web = "0.35.0"
shuttle-runtime = { version = "0.35.0", default-features = false }
tokio = "1.34.0"
futures-util = "0.3.29"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
serde = { version = "1.0.193", features = ["derive"] }

[dev-dependencies]
reqwest = "0.11.22"
serde_json = "1.0.108"
