[package]
name = "cch"
version = "2023.12.1-2"
authors = ["Francisco Nevitt Gonçalves <github.com/fng97>"]
edition = "2021"

[dependencies]
actix-web = "4.4.0"
shuttle-actix-web = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.34.0"
futures-util = "0.3.29"

[dev-dependencies]
reqwest = "0.11.22"
